"""pipenv ToolPlugin — wraps the `pipenv` CLI."""

from __future__ import annotations

from pip_ui.models import ArgSpec, CommandSpec, SafetyLevel
from pip_ui.tools import ToolPlugin

_GROUPS = ["Dependencies", "Environment", "Lockfile", "Utilities"]

_SPECS: dict[str, CommandSpec] = {
    "pipenv_install": CommandSpec(
        name="pipenv_install",
        label="Install",
        group="Dependencies",
        description="Install packages and add them to Pipfile, or install all from Pipfile.lock.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to install (leave blank to install from Pipfile.lock).",
                default=None,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev Packages",
                help="Install both dev and default packages.",
                default=False,
            ),
            ArgSpec(
                name="requirements",
                flag="--requirements",
                field_type="file",
                label="Requirements File",
                help="Import a requirements.txt file.",
                default=None,
            ),
            ArgSpec(
                name="editable",
                flag="--editable",
                field_type="dir",
                label="Editable Path",
                help="An editable Python package path.",
                default=None,
            ),
            ArgSpec(
                name="python",
                flag="--python",
                field_type="text",
                label="Python Version",
                help="Python version for the virtualenv (e.g. 3.11).",
                default=None,
            ),
            ArgSpec(
                name="pre",
                flag="--pre",
                field_type="checkbox",
                label="Allow Prereleases",
                help="Allow pre-release packages.",
                default=False,
            ),
            ArgSpec(
                name="deploy",
                flag="--deploy",
                field_type="checkbox",
                label="Deploy Mode",
                help="Abort if Pipfile.lock is out-of-date.",
                default=False,
            ),
            ArgSpec(
                name="skip_lock",
                flag="--skip-lock",
                field_type="checkbox",
                label="Skip Lock",
                help="Install from Pipfile, bypassing the lock mechanism.",
                default=False,
            ),
            ArgSpec(
                name="index",
                flag="--index",
                field_type="text",
                label="Index URL",
                help="Target package index URL.",
                default=None,
            ),
        ],
    ),
    "pipenv_uninstall": CommandSpec(
        name="pipenv_uninstall",
        label="Uninstall",
        group="Dependencies",
        description="Uninstall a package and remove it from Pipfile.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to uninstall (space-separated).",
                default=None,
            ),
            ArgSpec(
                name="all_dev",
                flag="--all-dev",
                field_type="checkbox",
                label="All Dev",
                help="Uninstall all dev packages.",
                default=False,
            ),
            ArgSpec(
                name="all",
                flag="--all",
                field_type="checkbox",
                label="All",
                help="Purge all packages from virtualenv (does not edit Pipfile).",
                default=False,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="From Dev",
                help="Uninstall from dev-packages.",
                default=False,
            ),
        ],
    ),
    "pipenv_upgrade": CommandSpec(
        name="pipenv_upgrade",
        label="Upgrade",
        group="Dependencies",
        description="Resolve and upgrade packages, updating Pipfile.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to upgrade (space-separated).",
                default=None,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev",
                help="Include dev packages.",
                default=False,
            ),
        ],
    ),
    "pipenv_update": CommandSpec(
        name="pipenv_update",
        label="Update",
        group="Dependencies",
        description="Run lock then sync — re-lock and install all packages.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        supports_dry_run=True,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to update (leave blank for all).",
                default=None,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev",
                help="Include dev packages.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="List packages that would be updated without updating.",
                default=False,
            ),
            ArgSpec(
                name="outdated",
                flag="--outdated",
                field_type="checkbox",
                label="Outdated",
                help="List out-of-date dependencies.",
                default=False,
            ),
        ],
    ),
    "pipenv_sync": CommandSpec(
        name="pipenv_sync",
        label="Sync",
        group="Dependencies",
        description="Install all packages specified in Pipfile.lock.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev",
                help="Install both dev and default packages.",
                default=False,
            ),
            ArgSpec(
                name="categories",
                flag="--categories",
                field_type="text",
                label="Categories",
                help="Space/comma-separated list of dependency categories.",
                default=None,
            ),
        ],
    ),
    "pipenv_clean": CommandSpec(
        name="pipenv_clean",
        label="Clean",
        group="Dependencies",
        description="Uninstall all packages not specified in Pipfile.lock.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        supports_dry_run=True,
        args=[
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="List packages to be removed without removing them.",
                default=False,
            ),
        ],
    ),
    "pipenv_lock": CommandSpec(
        name="pipenv_lock",
        label="Lock",
        group="Lockfile",
        description="Generate Pipfile.lock.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev",
                help="Generate both develop and default requirements.",
                default=False,
            ),
            ArgSpec(
                name="dev_only",
                flag="--dev-only",
                field_type="checkbox",
                label="Dev Only",
                help="Emit development dependencies only.",
                default=False,
            ),
            ArgSpec(
                name="pre",
                flag="--pre",
                field_type="checkbox",
                label="Allow Prereleases",
                help="Allow pre-release packages.",
                default=False,
            ),
            ArgSpec(
                name="categories",
                flag="--categories",
                field_type="text",
                label="Categories",
                help="Space/comma-separated list of dependency categories.",
                default=None,
            ),
        ],
    ),
    "pipenv_verify": CommandSpec(
        name="pipenv_verify",
        label="Verify",
        group="Lockfile",
        description="Verify the hash in Pipfile.lock is up-to-date.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "pipenv_requirements": CommandSpec(
        name="pipenv_requirements",
        label="Requirements",
        group="Lockfile",
        description="Generate a requirements.txt from Pipfile.lock.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev",
                help="Include dev packages.",
                default=False,
            ),
            ArgSpec(
                name="dev_only",
                flag="--dev-only",
                field_type="checkbox",
                label="Dev Only",
                help="Emit development dependencies only.",
                default=False,
            ),
            ArgSpec(
                name="hash",
                flag="--hash",
                field_type="checkbox",
                label="Include Hashes",
                help="Add package hashes to the output.",
                default=False,
            ),
            ArgSpec(
                name="exclude_markers",
                flag="--exclude-markers",
                field_type="checkbox",
                label="Exclude Markers",
                help="Strip environment markers from output.",
                default=False,
            ),
            ArgSpec(
                name="from_pipfile",
                flag="--from-pipfile",
                field_type="checkbox",
                label="From Pipfile",
                help="Generate from Pipfile instead of Pipfile.lock.",
                default=False,
            ),
        ],
    ),
    "pipenv_graph": CommandSpec(
        name="pipenv_graph",
        label="Graph",
        group="Utilities",
        description="Display the currently-installed dependency graph.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="json",
                flag="--json",
                field_type="checkbox",
                label="JSON Output",
                help="Output as JSON.",
                default=False,
            ),
            ArgSpec(
                name="json_tree",
                flag="--json-tree",
                field_type="checkbox",
                label="JSON Tree",
                help="Output as nested JSON tree.",
                default=False,
            ),
            ArgSpec(
                name="reverse",
                flag="--reverse",
                field_type="checkbox",
                label="Reverse",
                help="Reverse the dependency graph.",
                default=False,
            ),
        ],
    ),
    "pipenv_run": CommandSpec(
        name="pipenv_run",
        label="Run",
        group="Utilities",
        description="Spawn a command installed into the virtualenv.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="command",
                flag="",
                field_type="text",
                label="Command",
                help="Command to run inside the virtualenv.",
                default=None,
                required=True,
            ),
        ],
    ),
    "pipenv_audit": CommandSpec(
        name="pipenv_audit",
        label="Audit",
        group="Utilities",
        description="Audit packages for security vulnerabilities using pip-audit.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "pipenv_scripts": CommandSpec(
        name="pipenv_scripts",
        label="Scripts",
        group="Utilities",
        description="List scripts defined in the current environment config.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "pipenv_where": CommandSpec(
        name="pipenv_where",
        label="Where",
        group="Utilities",
        description="Output project home information.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "pipenv_venv": CommandSpec(
        name="pipenv_venv",
        label="Venv Path",
        group="Environment",
        description="Output virtualenv information (path).",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "pipenv_rm": CommandSpec(
        name="pipenv_rm",
        label="Remove Venv",
        group="Environment",
        description="Remove the virtualenv for the current project.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="python",
                flag="--python",
                field_type="text",
                label="Python Version",
                help="Python version of the virtualenv to remove.",
                default=None,
            ),
        ],
    ),
}

PIPENV_PLUGIN = ToolPlugin(
    name="pipenv",
    label="pipenv",
    extra="pipenv",
    run_via="global_cli",
    executable="pipenv",
    command_specs=_SPECS,
    command_groups=_GROUPS,
    help_url="https://pipenv.pypa.io/en/latest/",
    is_project_scoped=True,
)
