"""poetry ToolPlugin — wraps the `poetry` CLI."""

from __future__ import annotations

from pip_ui.models import ArgSpec, CommandSpec, SafetyLevel
from pip_ui.tools import ToolPlugin

_GROUPS = ["Dependencies", "Environment", "Build", "Publish", "Project"]

_SPECS: dict[str, CommandSpec] = {
    "poetry_add": CommandSpec(
        name="poetry_add",
        label="Add",
        group="Dependencies",
        description="Add a new dependency to pyproject.toml and install it.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        supports_dry_run=True,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to add (e.g. requests requests@^2.23.0).",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="group",
                flag="--group",
                field_type="text",
                label="Group",
                help="Dependency group to add to (default: main).",
                default=None,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev Dependency",
                help="Add as a development dependency (shortcut for --group dev).",
                default=False,
            ),
            ArgSpec(
                name="extras",
                flag="--extras",
                field_type="text",
                label="Extras",
                help="Extras to activate for the dependency.",
                default=None,
            ),
            ArgSpec(
                name="optional",
                flag="--optional",
                field_type="text",
                label="Optional Extra",
                help="Add as an optional dependency to this extra.",
                default=None,
            ),
            ArgSpec(
                name="allow_prereleases",
                flag="--allow-prereleases",
                field_type="checkbox",
                label="Allow Prereleases",
                help="Accept prereleases.",
                default=False,
            ),
            ArgSpec(
                name="lock",
                flag="--lock",
                field_type="checkbox",
                label="Lock Only",
                help="Update the lockfile only, do not install.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Output operations without executing them.",
                default=False,
            ),
        ],
    ),
    "poetry_remove": CommandSpec(
        name="poetry_remove",
        label="Remove",
        group="Dependencies",
        description="Remove a package from the project dependencies.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        supports_dry_run=True,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to remove (space-separated).",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="group",
                flag="--group",
                field_type="text",
                label="Group",
                help="Dependency group to remove from.",
                default=None,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev Dependency",
                help="Remove from development dependencies.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Output operations without executing them.",
                default=False,
            ),
        ],
    ),
    "poetry_install": CommandSpec(
        name="poetry_install",
        label="Install",
        group="Dependencies",
        description="Install project dependencies from poetry.lock (or pyproject.toml if no lock).",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="without",
                flag="--without",
                field_type="text",
                label="Without Groups",
                help="Dependency groups to ignore (comma-separated).",
                default=None,
            ),
            ArgSpec(
                name="with_groups",
                flag="--with",
                field_type="text",
                label="With Groups",
                help="Optional dependency groups to include (comma-separated).",
                default=None,
            ),
            ArgSpec(
                name="only",
                flag="--only",
                field_type="text",
                label="Only Groups",
                help="Only install these dependency groups (comma-separated).",
                default=None,
            ),
            ArgSpec(
                name="no_root",
                flag="--no-root",
                field_type="checkbox",
                label="No Root",
                help="Do not install the root package (current project).",
                default=False,
            ),
            ArgSpec(
                name="all_extras",
                flag="--all-extras",
                field_type="checkbox",
                label="All Extras",
                help="Install all extra dependencies.",
                default=False,
            ),
            ArgSpec(
                name="all_groups",
                flag="--all-groups",
                field_type="checkbox",
                label="All Groups",
                help="Install dependencies from all groups.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Output operations without executing them.",
                default=False,
            ),
            ArgSpec(
                name="compile",
                flag="--compile",
                field_type="checkbox",
                label="Compile",
                help="Compile Python source files to bytecode.",
                default=False,
            ),
        ],
    ),
    "poetry_update": CommandSpec(
        name="poetry_update",
        label="Update",
        group="Dependencies",
        description="Update dependencies according to pyproject.toml version constraints.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        supports_dry_run=True,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Specific packages to update (leave blank for all).",
                default=None,
            ),
            ArgSpec(
                name="without",
                flag="--without",
                field_type="text",
                label="Without Groups",
                help="Dependency groups to ignore (comma-separated).",
                default=None,
            ),
            ArgSpec(
                name="with_groups",
                flag="--with",
                field_type="text",
                label="With Groups",
                help="Optional dependency groups to include (comma-separated).",
                default=None,
            ),
            ArgSpec(
                name="lock",
                flag="--lock",
                field_type="checkbox",
                label="Lock Only",
                help="Update the lockfile only, do not install.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Output operations without executing them.",
                default=False,
            ),
        ],
    ),
    "poetry_show": CommandSpec(
        name="poetry_show",
        label="Show",
        group="Dependencies",
        description="Show information about packages.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="package",
                flag="",
                field_type="text",
                label="Package",
                help="Package to inspect (leave blank for all).",
                default=None,
            ),
            ArgSpec(
                name="tree",
                flag="--tree",
                field_type="checkbox",
                label="Tree",
                help="List dependencies as a tree.",
                default=False,
            ),
            ArgSpec(
                name="latest",
                flag="--latest",
                field_type="checkbox",
                label="Latest",
                help="Show the latest available version.",
                default=False,
            ),
            ArgSpec(
                name="outdated",
                flag="--outdated",
                field_type="checkbox",
                label="Outdated Only",
                help="Show only packages that are outdated.",
                default=False,
            ),
            ArgSpec(
                name="top_level",
                flag="--top-level",
                field_type="checkbox",
                label="Top-Level Only",
                help="Show only top-level dependencies.",
                default=False,
            ),
        ],
    ),
    "poetry_lock": CommandSpec(
        name="poetry_lock",
        label="Lock",
        group="Dependencies",
        description="Lock project dependencies (create or update poetry.lock).",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="regenerate",
                flag="--regenerate",
                field_type="checkbox",
                label="Regenerate",
                help="Ignore existing lock file and create a new one from scratch.",
                default=False,
            ),
        ],
    ),
    "poetry_check": CommandSpec(
        name="poetry_check",
        label="Check",
        group="Project",
        description="Validate pyproject.toml and its consistency with poetry.lock.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="lock",
                flag="--lock",
                field_type="checkbox",
                label="Check Lock",
                help="Verify that poetry.lock exists and is consistent.",
                default=False,
            ),
            ArgSpec(
                name="strict",
                flag="--strict",
                field_type="checkbox",
                label="Strict",
                help="Fail if check reports warnings.",
                default=False,
            ),
        ],
    ),
    "poetry_env_info": CommandSpec(
        name="poetry_env_info",
        label="Env Info",
        group="Environment",
        description="Display information about the current virtual environment.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="path",
                flag="--path",
                field_type="checkbox",
                label="Path Only",
                help="Only display the environment's path.",
                default=False,
            ),
        ],
    ),
    "poetry_env_list": CommandSpec(
        name="poetry_env_list",
        label="Env List",
        group="Environment",
        description="List all virtualenvs associated with the current project.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="full_path",
                flag="--full-path",
                field_type="checkbox",
                label="Full Path",
                help="Output the full paths of the virtualenvs.",
                default=False,
            ),
        ],
    ),
    "poetry_env_use": CommandSpec(
        name="poetry_env_use",
        label="Env Use",
        group="Environment",
        description="Activate or create a virtualenv for the current project.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="python",
                flag="",
                field_type="text",
                label="Python",
                help="Python executable to use (e.g. python3.11, /usr/bin/python3).",
                default=None,
                required=True,
            ),
        ],
    ),
    "poetry_env_remove": CommandSpec(
        name="poetry_env_remove",
        label="Env Remove",
        group="Environment",
        description="Remove virtual environments associated with the project.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="python",
                flag="",
                field_type="text",
                label="Python / Env Name",
                help="Python executable or virtualenv name to remove.",
                default=None,
            ),
            ArgSpec(
                name="all",
                flag="--all",
                field_type="checkbox",
                label="Remove All",
                help="Remove all managed virtual environments for this project.",
                default=False,
            ),
        ],
    ),
    "poetry_build": CommandSpec(
        name="poetry_build",
        label="Build",
        group="Build",
        description="Build the project as a tarball and/or wheel.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="format",
                flag="--format",
                field_type="dropdown",
                label="Format",
                help="Limit the format to either sdist or wheel.",
                default=None,
                choices=["", "sdist", "wheel"],
            ),
            ArgSpec(
                name="clean",
                flag="--clean",
                field_type="checkbox",
                label="Clean",
                help="Clean output directory before building.",
                default=False,
            ),
            ArgSpec(
                name="output",
                flag="--output",
                field_type="dir",
                label="Output Dir",
                help="Output directory for build artifacts (default: dist).",
                default=None,
            ),
        ],
    ),
    "poetry_publish": CommandSpec(
        name="poetry_publish",
        label="Publish",
        group="Publish",
        description="Publish the package to a remote repository.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="repository",
                flag="--repository",
                field_type="text",
                label="Repository",
                help="Repository to publish to (configured name, default: pypi).",
                default=None,
            ),
            ArgSpec(
                name="username",
                flag="--username",
                field_type="text",
                label="Username",
                help="Username to access the repository.",
                default=None,
            ),
            ArgSpec(
                name="password",
                flag="--password",
                field_type="secret",
                label="Password",
                help="Password to access the repository. Hidden in output and history.",
                default=None,
            ),
            ArgSpec(
                name="build",
                flag="--build",
                field_type="checkbox",
                label="Build First",
                help="Build the package before publishing.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Perform all actions except upload.",
                default=False,
            ),
            ArgSpec(
                name="skip_existing",
                flag="--skip-existing",
                field_type="checkbox",
                label="Skip Existing",
                help="Ignore errors from files already existing in the repository.",
                default=False,
            ),
        ],
    ),
    "poetry_version": CommandSpec(
        name="poetry_version",
        label="Version",
        group="Project",
        description="Show or bump the project version.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="bump",
                flag="",
                field_type="dropdown",
                label="Bump Rule",
                help="Bump rule or explicit version. Leave blank to just show current version.",
                default=None,
                choices=["", "patch", "minor", "major", "prepatch", "preminor", "premajor", "prerelease"],
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Output the new version without actually updating.",
                default=False,
            ),
        ],
    ),
    "poetry_run": CommandSpec(
        name="poetry_run",
        label="Run",
        group="Project",
        description="Run a command inside the project's virtual environment.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="command",
                flag="",
                field_type="text",
                label="Command",
                help="Command to run (e.g. pytest, python -m mypackage).",
                default=None,
                required=True,
            ),
        ],
    ),
}

POETRY_PLUGIN = ToolPlugin(
    name="poetry",
    label="poetry",
    extra="poetry",
    run_via="global_cli",
    executable="poetry",
    command_specs=_SPECS,
    command_groups=_GROUPS,
    help_url="https://python-poetry.org/docs/cli/",
    secret_flags=["--password"],
    is_project_scoped=True,
)
