"""uv ToolPlugin — wraps the `uv` CLI."""

from __future__ import annotations

from pip_ui.models import ArgSpec, CommandSpec, SafetyLevel
from pip_ui.tools import ToolPlugin

_GROUPS = ["Dependencies", "Environment", "Build", "Publish", "Python", "Cache"]

_SPECS: dict[str, CommandSpec] = {
    "uv_add": CommandSpec(
        name="uv_add",
        label="Add",
        group="Dependencies",
        description="Add dependencies to the project (updates pyproject.toml and uv.lock).",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to add as PEP 508 requirements (e.g. ruff==0.5.0).",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev Dependency",
                help="Add to the development dependency group.",
                default=False,
            ),
            ArgSpec(
                name="group",
                flag="--group",
                field_type="text",
                label="Group",
                help="Add to the specified dependency group.",
                default=None,
            ),
            ArgSpec(
                name="optional",
                flag="--optional",
                field_type="text",
                label="Optional Extra",
                help="Add to the package's optional dependencies for this extra.",
                default=None,
            ),
            ArgSpec(
                name="editable",
                flag="--editable",
                field_type="checkbox",
                label="Editable",
                help="Add as an editable dependency.",
                default=False,
            ),
            ArgSpec(
                name="requirements",
                flag="--requirements",
                field_type="file",
                label="Requirements File",
                help="Add packages listed in this file.",
                default=None,
            ),
            ArgSpec(
                name="bounds",
                flag="--bounds",
                field_type="dropdown",
                label="Version Bounds",
                help="Kind of version specifier to use.",
                default=None,
                choices=["", "lower", "major", "minor", "exact"],
            ),
            ArgSpec(
                name="no_sync",
                flag="--no-sync",
                field_type="checkbox",
                label="No Sync",
                help="Avoid syncing the virtual environment after adding.",
                default=False,
            ),
            ArgSpec(
                name="frozen",
                flag="--frozen",
                field_type="checkbox",
                label="Frozen",
                help="Add without re-locking the project.",
                default=False,
            ),
        ],
    ),
    "uv_remove": CommandSpec(
        name="uv_remove",
        label="Remove",
        group="Dependencies",
        description="Remove dependencies from the project.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Dependency names to remove (e.g. ruff).",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="dev",
                flag="--dev",
                field_type="checkbox",
                label="Dev Dependency",
                help="Remove from the development dependency group.",
                default=False,
            ),
            ArgSpec(
                name="group",
                flag="--group",
                field_type="text",
                label="Group",
                help="Remove from the specified dependency group.",
                default=None,
            ),
            ArgSpec(
                name="optional",
                flag="--optional",
                field_type="text",
                label="Optional Extra",
                help="Remove from the package's optional dependencies for this extra.",
                default=None,
            ),
            ArgSpec(
                name="no_sync",
                flag="--no-sync",
                field_type="checkbox",
                label="No Sync",
                help="Avoid syncing the virtual environment after removing.",
                default=False,
            ),
        ],
    ),
    "uv_sync": CommandSpec(
        name="uv_sync",
        label="Sync",
        group="Dependencies",
        description="Update the project's virtual environment to match the lockfile.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="all_extras",
                flag="--all-extras",
                field_type="checkbox",
                label="All Extras",
                help="Include all optional dependencies.",
                default=False,
            ),
            ArgSpec(
                name="no_dev",
                flag="--no-dev",
                field_type="checkbox",
                label="No Dev",
                help="Disable the development dependency group.",
                default=False,
            ),
            ArgSpec(
                name="group",
                flag="--group",
                field_type="text",
                label="Group",
                help="Include dependencies from this dependency group.",
                default=None,
            ),
            ArgSpec(
                name="all_groups",
                flag="--all-groups",
                field_type="checkbox",
                label="All Groups",
                help="Include dependencies from all dependency groups.",
                default=False,
            ),
            ArgSpec(
                name="frozen",
                flag="--frozen",
                field_type="checkbox",
                label="Frozen",
                help="Sync without updating the lockfile.",
                default=False,
            ),
            ArgSpec(
                name="no_install_project",
                flag="--no-install-project",
                field_type="checkbox",
                label="No Install Project",
                help="Do not install the current project.",
                default=False,
            ),
            ArgSpec(
                name="inexact",
                flag="--inexact",
                field_type="checkbox",
                label="Inexact",
                help="Do not remove extraneous packages.",
                default=False,
            ),
        ],
    ),
    "uv_lock": CommandSpec(
        name="uv_lock",
        label="Lock",
        group="Dependencies",
        description="Update the project's lockfile (uv.lock).",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="check",
                flag="--check",
                field_type="checkbox",
                label="Check",
                help="Check if the lockfile is up-to-date without updating.",
                default=False,
            ),
            ArgSpec(
                name="upgrade",
                flag="--upgrade",
                field_type="checkbox",
                label="Upgrade",
                help="Allow package upgrades, ignoring pinned versions.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Perform a dry run without writing the lockfile.",
                default=False,
            ),
        ],
    ),
    "uv_tree": CommandSpec(
        name="uv_tree",
        label="Tree",
        group="Dependencies",
        description="Display the project's dependency tree.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="depth",
                flag="--depth",
                field_type="text",
                label="Depth",
                help="Maximum display depth of the dependency tree.",
                default=None,
            ),
            ArgSpec(
                name="package",
                flag="--package",
                field_type="text",
                label="Package",
                help="Display only the specified package.",
                default=None,
            ),
            ArgSpec(
                name="invert",
                flag="--invert",
                field_type="checkbox",
                label="Invert",
                help="Show reverse dependencies (what depends on a given package).",
                default=False,
            ),
            ArgSpec(
                name="outdated",
                flag="--outdated",
                field_type="checkbox",
                label="Outdated",
                help="Show the latest available version of each package.",
                default=False,
            ),
            ArgSpec(
                name="no_dev",
                flag="--no-dev",
                field_type="checkbox",
                label="No Dev",
                help="Disable the development dependency group.",
                default=False,
            ),
        ],
    ),
    "uv_export": CommandSpec(
        name="uv_export",
        label="Export",
        group="Dependencies",
        description="Export the project's lockfile to an alternate format (e.g. requirements.txt).",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="format",
                flag="--format",
                field_type="dropdown",
                label="Format",
                help="Export format.",
                default="requirements.txt",
                choices=["requirements.txt", "pylock.toml", "cyclonedx1.5"],
            ),
            ArgSpec(
                name="all_extras",
                flag="--all-extras",
                field_type="checkbox",
                label="All Extras",
                help="Include all optional dependencies.",
                default=False,
            ),
            ArgSpec(
                name="no_dev",
                flag="--no-dev",
                field_type="checkbox",
                label="No Dev",
                help="Exclude development dependencies.",
                default=False,
            ),
            ArgSpec(
                name="all_groups",
                flag="--all-groups",
                field_type="checkbox",
                label="All Groups",
                help="Include all dependency groups.",
                default=False,
            ),
            ArgSpec(
                name="no_annotate",
                flag="--no-annotate",
                field_type="checkbox",
                label="No Annotations",
                help="Exclude comment annotations indicating the source of each package.",
                default=False,
            ),
            ArgSpec(
                name="no_header",
                flag="--no-header",
                field_type="checkbox",
                label="No Header",
                help="Exclude the comment header at the top of the generated output.",
                default=False,
            ),
        ],
    ),
    "uv_run": CommandSpec(
        name="uv_run",
        label="Run",
        group="Dependencies",
        description="Run a command or script in the project's environment.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="command",
                flag="",
                field_type="text",
                label="Command",
                help="Command or script to run.",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="with_packages",
                flag="--with",
                field_type="multi",
                label="With Packages",
                help="Run with additional packages installed (space-separated).",
                default=None,
            ),
            ArgSpec(
                name="no_dev",
                flag="--no-dev",
                field_type="checkbox",
                label="No Dev",
                help="Disable the development dependency group.",
                default=False,
            ),
            ArgSpec(
                name="all_groups",
                flag="--all-groups",
                field_type="checkbox",
                label="All Groups",
                help="Include all dependency groups.",
                default=False,
            ),
            ArgSpec(
                name="env_file",
                flag="--env-file",
                field_type="file",
                label="Env File",
                help="Load environment variables from this .env file.",
                default=None,
            ),
        ],
    ),
    "uv_venv": CommandSpec(
        name="uv_venv",
        label="Create Venv",
        group="Environment",
        description="Create a virtual environment.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="path",
                flag="",
                field_type="dir",
                label="Path",
                help="Path for the virtual environment (default: .venv).",
                default=".venv",
            ),
            ArgSpec(
                name="python",
                flag="--python",
                field_type="text",
                label="Python",
                help="Python interpreter to use (e.g. 3.11, python3.11).",
                default=None,
            ),
            ArgSpec(
                name="seed",
                flag="--seed",
                field_type="checkbox",
                label="Seed Packages",
                help="Install seed packages (pip, setuptools, wheel) into the venv.",
                default=False,
            ),
            ArgSpec(
                name="clear",
                flag="--clear",
                field_type="checkbox",
                label="Clear",
                help="Remove existing files or directories at the target path.",
                default=False,
            ),
            ArgSpec(
                name="system_site_packages",
                flag="--system-site-packages",
                field_type="checkbox",
                label="System Site Packages",
                help="Give the venv access to the system site-packages directory.",
                default=False,
            ),
            ArgSpec(
                name="prompt",
                flag="--prompt",
                field_type="text",
                label="Prompt",
                help="Alternative prompt prefix for the virtual environment.",
                default=None,
            ),
        ],
    ),
    "uv_build": CommandSpec(
        name="uv_build",
        label="Build",
        group="Build",
        description="Build Python packages into source distributions and wheels.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="src",
                flag="",
                field_type="dir",
                label="Source",
                help="Directory from which to build (default: current project).",
                default=None,
            ),
            ArgSpec(
                name="sdist",
                flag="--sdist",
                field_type="checkbox",
                label="sdist Only",
                help="Build a source distribution only.",
                default=False,
            ),
            ArgSpec(
                name="wheel",
                flag="--wheel",
                field_type="checkbox",
                label="Wheel Only",
                help="Build a binary distribution (wheel) only.",
                default=False,
            ),
            ArgSpec(
                name="out_dir",
                flag="--out-dir",
                field_type="dir",
                label="Output Dir",
                help="Output directory for built distributions.",
                default=None,
            ),
            ArgSpec(
                name="clear",
                flag="--clear",
                field_type="checkbox",
                label="Clear",
                help="Clear the output directory before building.",
                default=False,
            ),
            ArgSpec(
                name="python",
                flag="--python",
                field_type="text",
                label="Python",
                help="Python interpreter to use for the build environment.",
                default=None,
            ),
        ],
    ),
    "uv_publish": CommandSpec(
        name="uv_publish",
        label="Publish",
        group="Publish",
        description="Upload distributions to a package index.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="files",
                flag="",
                field_type="multi",
                label="Files",
                help="Paths or glob expressions for files to upload (default: dist/*).",
                default=None,
            ),
            ArgSpec(
                name="index",
                flag="--index",
                field_type="text",
                label="Index",
                help="Named index from configuration to publish to.",
                default=None,
            ),
            ArgSpec(
                name="publish_url",
                flag="--publish-url",
                field_type="text",
                label="Publish URL",
                help="URL of the upload endpoint.",
                default=None,
            ),
            ArgSpec(
                name="username",
                flag="--username",
                field_type="text",
                label="Username",
                help="Username for the upload.",
                default=None,
            ),
            ArgSpec(
                name="password",
                flag="--password",
                field_type="secret",
                label="Password",
                help="Password for the upload. Hidden in output and history.",
                default=None,
            ),
            ArgSpec(
                name="token",
                flag="--token",
                field_type="secret",
                label="Token",
                help="API token for the upload. Hidden in output and history.",
                default=None,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Perform a dry run without uploading files.",
                default=False,
            ),
        ],
    ),
    "uv_python_list": CommandSpec(
        name="uv_python_list",
        label="Python List",
        group="Python",
        description="List available Python installations.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="only_installed",
                flag="--only-installed",
                field_type="checkbox",
                label="Installed Only",
                help="Only show installed Python versions.",
                default=False,
            ),
            ArgSpec(
                name="all_versions",
                flag="--all-versions",
                field_type="checkbox",
                label="All Versions",
                help="List all Python versions including old patch versions.",
                default=False,
            ),
        ],
    ),
    "uv_python_install": CommandSpec(
        name="uv_python_install",
        label="Python Install",
        group="Python",
        description="Download and install a Python version.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="version",
                flag="",
                field_type="text",
                label="Version",
                help="Python version to install (e.g. 3.11, 3.12.0).",
                default=None,
                required=True,
            ),
        ],
    ),
    "uv_python_pin": CommandSpec(
        name="uv_python_pin",
        label="Python Pin",
        group="Python",
        description="Pin to a specific Python version for this project.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="version",
                flag="",
                field_type="text",
                label="Version",
                help="Python version to pin (e.g. 3.11).",
                default=None,
                required=True,
            ),
        ],
    ),
    "uv_cache_dir": CommandSpec(
        name="uv_cache_dir",
        label="Cache Dir",
        group="Cache",
        description="Show the uv cache directory.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "uv_cache_clean": CommandSpec(
        name="uv_cache_clean",
        label="Cache Clean",
        group="Cache",
        description="Clear the cache, removing all entries or entries for specific packages.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Specific packages to clear from cache (leave blank for all).",
                default=None,
            ),
        ],
    ),
    "uv_cache_prune": CommandSpec(
        name="uv_cache_prune",
        label="Cache Prune",
        group="Cache",
        description="Prune all unreachable objects from the cache.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[],
    ),
    "uv_version": CommandSpec(
        name="uv_version",
        label="Version",
        group="Dependencies",
        description="Read or update the project's version.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="value",
                flag="",
                field_type="text",
                label="Version",
                help="New version to set. Leave blank to read the current version.",
                default=None,
            ),
            ArgSpec(
                name="bump",
                flag="--bump",
                field_type="dropdown",
                label="Bump",
                help="Bump the version by a component.",
                default=None,
                choices=["", "major", "minor", "patch"],
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Show the new version without writing it.",
                default=False,
            ),
        ],
    ),
}

UV_PLUGIN = ToolPlugin(
    name="uv",
    label="uv",
    extra="uv",
    run_via="global_cli",
    executable="uv",
    command_specs=_SPECS,
    command_groups=_GROUPS,
    help_url="https://docs.astral.sh/uv/",
    secret_flags=["--password", "--token"],
    is_project_scoped=True,
)
