"""Command specifications for all supported pip commands."""

from __future__ import annotations

from pip_ui.models import ArgSpec, CommandSpec, SafetyLevel

COMMAND_GROUPS: list[str] = [
    "Package Management",
    "Information",
    "Index and Search",
    "Artifacts",
    "Configuration",
    "Cache",
    "Diagnostics",
]


def make_install_args() -> list[ArgSpec]:
    return [
        ArgSpec(
            name="packages",
            flag="",
            field_type="multi",
            label="Packages",
            help="One or more package names to install (e.g. requests==2.28.0).",
            default=None,
            required=False,
        ),
        ArgSpec(
            name="requirements_file",
            flag="-r",
            field_type="file",
            label="Requirements File",
            help="Install from the given requirements file.",
            default=None,
        ),
        ArgSpec(
            name="constraints_file",
            flag="-c",
            field_type="file",
            label="Constraints File",
            help="Constrain versions using the given constraints file.",
            default=None,
        ),
        ArgSpec(
            name="editable",
            flag="-e",
            field_type="text",
            label="Editable (path/URL)",
            help="Install a project in editable mode from a local path or VCS URL.",
            default=None,
        ),
        ArgSpec(
            name="upgrade",
            flag="-U",
            field_type="checkbox",
            label="Upgrade",
            help="Upgrade all specified packages to the newest available version.",
            default=False,
        ),
        ArgSpec(
            name="upgrade_strategy",
            flag="--upgrade-strategy",
            field_type="dropdown",
            label="Upgrade Strategy",
            help="How to handle upgrading of dependencies.",
            default="only-if-needed",
            choices=["only-if-needed", "eager"],
        ),
        ArgSpec(
            name="force_reinstall",
            flag="--force-reinstall",
            field_type="checkbox",
            label="Force Reinstall",
            help="Reinstall all packages even if they are already up-to-date.",
            default=False,
        ),
        ArgSpec(
            name="ignore_installed",
            flag="-I",
            field_type="checkbox",
            label="Ignore Installed",
            help="Ignore the installed packages, overwriting files.",
            default=False,
        ),
        ArgSpec(
            name="user",
            flag="--user",
            field_type="checkbox",
            label="User Install",
            help="Install to the Python user install directory.",
            default=False,
        ),
        ArgSpec(
            name="target",
            flag="--target",
            field_type="dir",
            label="Target Directory",
            help="Install packages into the given directory.",
            default=None,
        ),
        ArgSpec(
            name="prefix",
            flag="--prefix",
            field_type="dir",
            label="Prefix",
            help="Installation prefix where lib, bin and other top-level folders are placed.",
            default=None,
        ),
        ArgSpec(
            name="index_url",
            flag="-i",
            field_type="text",
            label="Index URL",
            help="Base URL of the Python Package Index.",
            default=None,
        ),
        ArgSpec(
            name="extra_index_url",
            flag="--extra-index-url",
            field_type="multi",
            label="Extra Index URLs",
            help="Extra URLs of package indexes to use in addition to the primary one.",
            default=None,
        ),
        ArgSpec(
            name="no_index",
            flag="--no-index",
            field_type="checkbox",
            label="No Index",
            help="Ignore package index (only looking at --find-links URLs instead).",
            default=False,
        ),
        ArgSpec(
            name="find_links",
            flag="-f",
            field_type="text",
            label="Find Links",
            help="Look for archives in this directory or on this HTML page.",
            default=None,
        ),
        ArgSpec(
            name="trusted_host",
            flag="--trusted-host",
            field_type="text",
            label="Trusted Host",
            help="Mark this host or host:port pair as trusted.",
            default=None,
        ),
        ArgSpec(
            name="no_build_isolation",
            flag="--no-build-isolation",
            field_type="checkbox",
            label="No Build Isolation",
            help="Disable isolation when building a modern source distribution.",
            default=False,
        ),
        ArgSpec(
            name="no_binary",
            flag="--no-binary",
            field_type="text",
            label="No Binary",
            help="Comma-separated list of packages to install from source (':all:' for everything).",
            default=None,
        ),
        ArgSpec(
            name="only_binary",
            flag="--only-binary",
            field_type="text",
            label="Only Binary",
            help="Comma-separated list of packages to only install from wheels.",
            default=None,
        ),
        ArgSpec(
            name="no_cache_dir",
            flag="--no-cache-dir",
            field_type="checkbox",
            label="No Cache Dir",
            help="Disable the cache.",
            default=False,
        ),
        ArgSpec(
            name="break_system_packages",
            flag="--break-system-packages",
            field_type="checkbox",
            label="Break System Packages",
            help="Allow pip to modify an externally-managed Python install. Dangerous on system Python.",
            default=False,
        ),
        ArgSpec(
            name="pre",
            flag="--pre",
            field_type="checkbox",
            label="Pre-release",
            help="Include pre-release and development versions.",
            default=False,
        ),
        ArgSpec(
            name="dry_run",
            flag="--dry-run",
            field_type="checkbox",
            label="Dry Run",
            help="Don't actually install anything, just print what would be.",
            default=False,
        ),
        ArgSpec(
            name="report",
            flag="--report",
            field_type="text",
            label="Report File",
            help="Generate a JSON installation report to this path.",
            default=None,
        ),
    ]


COMMAND_SPECS: dict[str, CommandSpec] = {
    "install": CommandSpec(
        name="install",
        label="Install",
        group="Package Management",
        description="Install packages from PyPI or other sources.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        supports_dry_run=True,
        supports_report=True,
        args=make_install_args(),
    ),
    "uninstall": CommandSpec(
        name="uninstall",
        label="Uninstall",
        group="Package Management",
        description="Uninstall packages.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to uninstall.",
                default=None,
            ),
            ArgSpec(
                name="requirements_file",
                flag="-r",
                field_type="file",
                label="Requirements File",
                help="Uninstall all packages listed in the given requirements file.",
                default=None,
            ),
            ArgSpec(
                name="yes",
                flag="-y",
                field_type="checkbox",
                label="Yes (skip pip's confirmation)",
                help="Don't ask for confirmation of uninstall deletions.",
                default=False,
            ),
        ],
    ),
    "list": CommandSpec(
        name="list",
        label="List",
        group="Information",
        description="List installed packages.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="format",
                flag="--format",
                field_type="dropdown",
                label="Format",
                help="Select the output format.",
                default="columns",
                choices=["columns", "freeze", "json"],
            ),
            ArgSpec(
                name="outdated",
                flag="--outdated",
                field_type="checkbox",
                label="Outdated Only",
                help="List outdated packages.",
                default=False,
            ),
            ArgSpec(
                name="uptodate",
                flag="--uptodate",
                field_type="checkbox",
                label="Up-to-date Only",
                help="List up-to-date packages.",
                default=False,
            ),
            ArgSpec(
                name="editable",
                flag="--editable",
                field_type="checkbox",
                label="Editable Only",
                help="List editable projects.",
                default=False,
            ),
            ArgSpec(
                name="not_required",
                flag="--not-required",
                field_type="checkbox",
                label="Not Required",
                help="List packages that are not dependencies of installed packages.",
                default=False,
            ),
            ArgSpec(
                name="user",
                flag="--user",
                field_type="checkbox",
                label="User Only",
                help="Only output packages installed in user-site.",
                default=False,
            ),
        ],
    ),
    "show": CommandSpec(
        name="show",
        label="Show",
        group="Information",
        description="Show information about installed packages.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to show information for.",
                default=None,
            ),
            ArgSpec(
                name="files",
                flag="-f",
                field_type="checkbox",
                label="Show Files",
                help="Show the full list of installed files for each package.",
                default=False,
            ),
        ],
    ),
    "freeze": CommandSpec(
        name="freeze",
        label="Freeze",
        group="Information",
        description="Output installed packages in requirements format.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="local",
                flag="-l",
                field_type="checkbox",
                label="Local Only",
                help="If in a virtualenv, only report packages that are local to it.",
                default=False,
            ),
            ArgSpec(
                name="all",
                flag="--all",
                field_type="checkbox",
                label="All Packages",
                help="Do not skip these packages in the output (pip, setuptools, wheel, etc).",
                default=False,
            ),
            ArgSpec(
                name="exclude_editable",
                flag="--exclude-editable",
                field_type="checkbox",
                label="Exclude Editable",
                help="Exclude editable package from output.",
                default=False,
            ),
            ArgSpec(
                name="exclude",
                flag="--exclude",
                field_type="text",
                label="Exclude Package",
                help="Exclude the specified package from the output.",
                default=None,
            ),
        ],
    ),
    "check": CommandSpec(
        name="check",
        label="Check",
        group="Information",
        description="Verify installed packages have compatible dependencies.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "inspect": CommandSpec(
        name="inspect",
        label="Inspect",
        group="Information",
        description="Inspect the Python environment (pip inspect, JSON output).",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="local",
                flag="--local",
                field_type="checkbox",
                label="Local Only",
                help="If in a virtualenv, only report packages local to it.",
                default=False,
            ),
            ArgSpec(
                name="user",
                flag="--user",
                field_type="checkbox",
                label="User Only",
                help="Only report packages installed in user-site.",
                default=False,
            ),
        ],
    ),
    "index_versions": CommandSpec(
        name="index_versions",
        label="Index Versions",
        group="Index and Search",
        description="Show available versions of a package on the index.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="package",
                flag="",
                field_type="text",
                label="Package",
                help="Package name to look up.",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="pre",
                flag="--pre",
                field_type="checkbox",
                label="Include Pre-releases",
                help="Include pre-release and development versions.",
                default=False,
            ),
            ArgSpec(
                name="index_url",
                flag="-i",
                field_type="text",
                label="Index URL",
                help="Base URL of the Python Package Index.",
                default=None,
            ),
            ArgSpec(
                name="extra_index_url",
                flag="--extra-index-url",
                field_type="multi",
                label="Extra Index URLs",
                help="Extra URLs of package indexes.",
                default=None,
            ),
            ArgSpec(
                name="no_index",
                flag="--no-index",
                field_type="checkbox",
                label="No Index",
                help="Ignore package index (only use --find-links).",
                default=False,
            ),
            ArgSpec(
                name="find_links",
                flag="-f",
                field_type="text",
                label="Find Links",
                help="Look for archives in a directory or HTML page.",
                default=None,
            ),
        ],
    ),
    "download": CommandSpec(
        name="download",
        label="Download",
        group="Artifacts",
        description="Download packages (and their dependencies) without installing.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="One or more package specifiers.",
                default=None,
            ),
            ArgSpec(
                name="dest",
                flag="-d",
                field_type="dir",
                label="Destination Directory",
                help="Download packages into this directory.",
                default=None,
            ),
            ArgSpec(
                name="requirements_file",
                flag="-r",
                field_type="file",
                label="Requirements File",
                help="Install from the given requirements file.",
                default=None,
            ),
            ArgSpec(
                name="constraints_file",
                flag="-c",
                field_type="file",
                label="Constraints File",
                help="Constrain versions using the given constraints file.",
                default=None,
            ),
            ArgSpec(
                name="platform",
                flag="--platform",
                field_type="text",
                label="Platform",
                help="Only use wheels compatible with this platform.",
                default=None,
            ),
            ArgSpec(
                name="python_version",
                flag="--python-version",
                field_type="text",
                label="Python Version",
                help="The Python interpreter version to use for wheel and 'Requires-Python' compatibility checks.",
                default=None,
            ),
            ArgSpec(
                name="implementation",
                flag="--implementation",
                field_type="text",
                label="Implementation",
                help="Only use wheels compatible with the specified Python implementation (e.g. cp).",
                default=None,
            ),
            ArgSpec(
                name="abi",
                flag="--abi",
                field_type="text",
                label="ABI",
                help="Only use wheels compatible with this ABI (e.g. cp311).",
                default=None,
            ),
            ArgSpec(
                name="no_deps",
                flag="--no-deps",
                field_type="checkbox",
                label="No Dependencies",
                help="Don't download package dependencies.",
                default=False,
            ),
            ArgSpec(
                name="index_url",
                flag="-i",
                field_type="text",
                label="Index URL",
                help="Base URL of the Python Package Index.",
                default=None,
            ),
            ArgSpec(
                name="extra_index_url",
                flag="--extra-index-url",
                field_type="multi",
                label="Extra Index URLs",
                help="Extra URLs of package indexes.",
                default=None,
            ),
            ArgSpec(
                name="no_index",
                flag="--no-index",
                field_type="checkbox",
                label="No Index",
                help="Ignore package index (only use --find-links).",
                default=False,
            ),
            ArgSpec(
                name="find_links",
                flag="-f",
                field_type="text",
                label="Find Links",
                help="Look for archives in a directory or HTML page.",
                default=None,
            ),
        ],
    ),
    "wheel": CommandSpec(
        name="wheel",
        label="Wheel",
        group="Artifacts",
        description="Build wheels from a requirements file or package(s).",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Package specifiers to build wheels for.",
                default=None,
            ),
            ArgSpec(
                name="wheel_dir",
                flag="-w",
                field_type="dir",
                label="Wheel Directory",
                help="Output wheels into this directory.",
                default=None,
            ),
            ArgSpec(
                name="requirements_file",
                flag="-r",
                field_type="file",
                label="Requirements File",
                help="Build wheels for everything in the given requirements file.",
                default=None,
            ),
            ArgSpec(
                name="constraints_file",
                flag="-c",
                field_type="file",
                label="Constraints File",
                help="Constrain versions using the given constraints file.",
                default=None,
            ),
            ArgSpec(
                name="no_deps",
                flag="--no-deps",
                field_type="checkbox",
                label="No Dependencies",
                help="Don't build dependencies' wheels.",
                default=False,
            ),
        ],
    ),
    "lock": CommandSpec(
        name="lock",
        label="Lock",
        group="Artifacts",
        description="Generate a lockfile (requires recent pip). May not be supported by the selected pip.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Package specifiers to include in the lockfile.",
                default=None,
            ),
            ArgSpec(
                name="requirements_file",
                flag="-r",
                field_type="file",
                label="Requirements File",
                help="Lock everything in the given requirements file.",
                default=None,
            ),
        ],
    ),
    "config_list": CommandSpec(
        name="config_list",
        label="Config List",
        group="Configuration",
        description="List configuration values.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "config_debug": CommandSpec(
        name="config_debug",
        label="Config Debug",
        group="Configuration",
        description="Show configuration sources and effective values.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "config_get": CommandSpec(
        name="config_get",
        label="Config Get",
        group="Configuration",
        description="Get a configuration value by name.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="key",
                flag="",
                field_type="text",
                label="Key",
                help="Configuration key (e.g. global.index-url).",
                default=None,
                required=True,
            ),
        ],
    ),
    "config_set": CommandSpec(
        name="config_set",
        label="Config Set",
        group="Configuration",
        description="Set a configuration value (writes pip.conf).",
        safety_level=SafetyLevel.RISKY_CONFIG,
        args=[
            ArgSpec(
                name="scope",
                flag="--",
                field_type="dropdown",
                label="Scope",
                help="Where to write the value.",
                default="user",
                choices=["user", "global", "site"],
            ),
            ArgSpec(
                name="key",
                flag="",
                field_type="text",
                label="Key",
                help="Configuration key (e.g. global.index-url).",
                default=None,
                required=True,
            ),
            ArgSpec(
                name="value",
                flag="",
                field_type="text",
                label="Value",
                help="Configuration value.",
                default=None,
                required=True,
            ),
        ],
    ),
    "config_unset": CommandSpec(
        name="config_unset",
        label="Config Unset",
        group="Configuration",
        description="Remove a configuration value.",
        safety_level=SafetyLevel.RISKY_CONFIG,
        args=[
            ArgSpec(
                name="scope",
                flag="--",
                field_type="dropdown",
                label="Scope",
                help="Where to remove the value.",
                default="user",
                choices=["user", "global", "site"],
            ),
            ArgSpec(
                name="key",
                flag="",
                field_type="text",
                label="Key",
                help="Configuration key to remove.",
                default=None,
                required=True,
            ),
        ],
    ),
    "config_edit": CommandSpec(
        name="config_edit",
        label="Config Edit",
        group="Configuration",
        description="Open the pip config file in an external editor.",
        safety_level=SafetyLevel.RISKY_CONFIG,
        args=[
            ArgSpec(
                name="scope",
                flag="--",
                field_type="dropdown",
                label="Scope",
                help="Which config file to edit.",
                default="user",
                choices=["user", "global", "site"],
            ),
        ],
    ),
    "cache_dir": CommandSpec(
        name="cache_dir",
        label="Cache Dir",
        group="Cache",
        description="Show the cache directory.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "cache_info": CommandSpec(
        name="cache_info",
        label="Cache Info",
        group="Cache",
        description="Show information about the cache.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "cache_list": CommandSpec(
        name="cache_list",
        label="Cache List",
        group="Cache",
        description="List cached wheels.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="pattern",
                flag="",
                field_type="text",
                label="Pattern",
                help="Optional glob pattern (e.g. requests*).",
                default=None,
            ),
            ArgSpec(
                name="format",
                flag="--format",
                field_type="dropdown",
                label="Format",
                help="Output format.",
                default="human",
                choices=["human", "abspath"],
            ),
        ],
    ),
    "cache_remove": CommandSpec(
        name="cache_remove",
        label="Cache Remove",
        group="Cache",
        description="Remove items from the cache matching a pattern.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="pattern",
                flag="",
                field_type="text",
                label="Pattern",
                help="Glob pattern of cache entries to remove.",
                default=None,
                required=True,
            ),
        ],
    ),
    "cache_purge": CommandSpec(
        name="cache_purge",
        label="Cache Purge",
        group="Cache",
        description="Remove all items from the cache.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[],
    ),
    "debug": CommandSpec(
        name="debug",
        label="Debug",
        group="Diagnostics",
        description="Show debug information (pip debug).",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "version": CommandSpec(
        name="version",
        label="Version",
        group="Diagnostics",
        description="Show pip version information.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "help": CommandSpec(
        name="help",
        label="Help",
        group="Diagnostics",
        description="Show pip help.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
}


def get_commands_by_group() -> dict[str, list[CommandSpec]]:
    result: dict[str, list[CommandSpec]] = {g: [] for g in COMMAND_GROUPS}
    for spec in COMMAND_SPECS.values():
        if spec.group in result:
            result[spec.group].append(spec)
        else:
            result[spec.group] = [spec]
    return result


SPECIAL_ARGV: dict[str, list[str]] = {
    "config_list": ["config", "list"],
    "config_debug": ["config", "debug"],
    "cache_dir": ["cache", "dir"],
    "cache_info": ["cache", "info"],
    "cache_purge": ["cache", "purge"],
    "debug": ["debug"],
    "version": ["--version"],
    "help": ["help"],
}
