"""Command specifications for all supported pip commands."""

from __future__ import annotations

from pip_ui.models import ArgSpec, CommandSpec, SafetyLevel

COMMAND_GROUPS: list[str] = [
    "Package Management",
    "Information",
    "Configuration",
    "Cache",
    "Diagnostics",
]

COMMAND_SPECS: dict[str, CommandSpec] = {
    "install": CommandSpec(
        name="install",
        label="Install",
        group="Package Management",
        description="Install packages from PyPI or other sources.",
        safety_level=SafetyLevel.MODIFIES_ENV,
        supports_dry_run=True,
        supports_report=True,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="One or more package names to install (e.g. requests==2.28.0).",
                default=None,
                required=False,
            ),
            ArgSpec(
                name="requirements_file",
                flag="-r",
                field_type="file",
                label="Requirements File",
                help="Install from the given requirements file.",
                default=None,
            ),
            ArgSpec(
                name="editable",
                flag="-e",
                field_type="text",
                label="Editable (path/URL)",
                help="Install a project in editable mode from a local path or VCS URL.",
                default=None,
            ),
            ArgSpec(
                name="upgrade",
                flag="-U",
                field_type="checkbox",
                label="Upgrade",
                help="Upgrade all specified packages to the newest available version.",
                default=False,
            ),
            ArgSpec(
                name="force_reinstall",
                flag="--force-reinstall",
                field_type="checkbox",
                label="Force Reinstall",
                help="Reinstall all packages even if they are already up-to-date.",
                default=False,
            ),
            ArgSpec(
                name="user",
                flag="--user",
                field_type="checkbox",
                label="User Install",
                help="Install to the Python user install directory.",
                default=False,
            ),
            ArgSpec(
                name="index_url",
                flag="-i",
                field_type="text",
                label="Index URL",
                help="Base URL of the Python Package Index.",
                default=None,
            ),
            ArgSpec(
                name="extra_index_url",
                flag="--extra-index-url",
                field_type="multi",
                label="Extra Index URLs",
                help="Extra URLs of package indexes to use in addition to the primary one.",
                default=None,
            ),
            ArgSpec(
                name="no_index",
                flag="--no-index",
                field_type="checkbox",
                label="No Index",
                help="Ignore package index (only looking at --find-links URLs instead).",
                default=False,
            ),
            ArgSpec(
                name="find_links",
                flag="-f",
                field_type="text",
                label="Find Links",
                help="Look for archives in this directory or on this HTML page.",
                default=None,
            ),
            ArgSpec(
                name="trusted_host",
                flag="--trusted-host",
                field_type="text",
                label="Trusted Host",
                help="Mark this host or host:port pair as trusted.",
                default=None,
            ),
            ArgSpec(
                name="no_cache_dir",
                flag="--no-cache-dir",
                field_type="checkbox",
                label="No Cache Dir",
                help="Disable the cache.",
                default=False,
            ),
            ArgSpec(
                name="pre",
                flag="--pre",
                field_type="checkbox",
                label="Pre-release",
                help="Include pre-release and development versions.",
                default=False,
            ),
            ArgSpec(
                name="dry_run",
                flag="--dry-run",
                field_type="checkbox",
                label="Dry Run",
                help="Don't actually install anything, just print what would be.",
                default=False,
            ),
        ],
    ),
    "uninstall": CommandSpec(
        name="uninstall",
        label="Uninstall",
        group="Package Management",
        description="Uninstall packages.",
        safety_level=SafetyLevel.DESTRUCTIVE,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to uninstall.",
                default=None,
            ),
            ArgSpec(
                name="requirements_file",
                flag="-r",
                field_type="file",
                label="Requirements File",
                help="Uninstall all packages listed in the given requirements file.",
                default=None,
            ),
            ArgSpec(
                name="yes",
                flag="-y",
                field_type="checkbox",
                label="Yes (skip confirmation)",
                help="Don't ask for confirmation of uninstall deletions.",
                default=False,
            ),
        ],
    ),
    "list": CommandSpec(
        name="list",
        label="List",
        group="Information",
        description="List installed packages.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="format",
                flag="--format",
                field_type="dropdown",
                label="Format",
                help="Select the output format.",
                default="columns",
                choices=["columns", "freeze", "json", "tree"],
            ),
            ArgSpec(
                name="outdated",
                flag="--outdated",
                field_type="checkbox",
                label="Outdated Only",
                help="List outdated packages.",
                default=False,
            ),
            ArgSpec(
                name="uptodate",
                flag="--uptodate",
                field_type="checkbox",
                label="Up-to-date Only",
                help="List up-to-date packages.",
                default=False,
            ),
            ArgSpec(
                name="editable",
                flag="--editable",
                field_type="checkbox",
                label="Editable Only",
                help="List editable projects.",
                default=False,
            ),
            ArgSpec(
                name="not_required",
                flag="--not-required",
                field_type="checkbox",
                label="Not Required",
                help="List packages that are not dependencies of installed packages.",
                default=False,
            ),
        ],
    ),
    "show": CommandSpec(
        name="show",
        label="Show",
        group="Information",
        description="Show information about installed packages.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="packages",
                flag="",
                field_type="multi",
                label="Packages",
                help="Packages to show information for.",
                default=None,
            ),
            ArgSpec(
                name="files",
                flag="-f",
                field_type="checkbox",
                label="Show Files",
                help="Show the full list of installed files for each package.",
                default=False,
            ),
        ],
    ),
    "freeze": CommandSpec(
        name="freeze",
        label="Freeze",
        group="Information",
        description="Output installed packages in requirements format.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[
            ArgSpec(
                name="local",
                flag="-l",
                field_type="checkbox",
                label="Local Only",
                help="If in a virtualenv, only report packages that are local to it.",
                default=False,
            ),
            ArgSpec(
                name="exclude_editable",
                flag="--exclude-editable",
                field_type="checkbox",
                label="Exclude Editable",
                help="Exclude editable package from output.",
                default=False,
            ),
        ],
    ),
    "check": CommandSpec(
        name="check",
        label="Check",
        group="Information",
        description="Verify installed packages have compatible dependencies.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "config_list": CommandSpec(
        name="config_list",
        label="Config List",
        group="Configuration",
        description="List configuration values.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "config_debug": CommandSpec(
        name="config_debug",
        label="Config Debug",
        group="Configuration",
        description="Show configuration sources and effective values.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "cache_dir": CommandSpec(
        name="cache_dir",
        label="Cache Dir",
        group="Cache",
        description="Show the cache directory.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "cache_info": CommandSpec(
        name="cache_info",
        label="Cache Info",
        group="Cache",
        description="Show information about the cache.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "debug": CommandSpec(
        name="debug",
        label="Debug",
        group="Diagnostics",
        description="Show debug information (pip debug).",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "version": CommandSpec(
        name="version",
        label="Version",
        group="Diagnostics",
        description="Show pip version information.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
    "help": CommandSpec(
        name="help",
        label="Help",
        group="Diagnostics",
        description="Show pip help.",
        safety_level=SafetyLevel.READ_ONLY,
        args=[],
    ),
}


def get_commands_by_group() -> dict[str, list[CommandSpec]]:
    result: dict[str, list[CommandSpec]] = {g: [] for g in COMMAND_GROUPS}
    for spec in COMMAND_SPECS.values():
        if spec.group in result:
            result[spec.group].append(spec)
        else:
            result[spec.group] = [spec]
    return result
